-- Forum 表
CREATE TABLE IF NOT EXISTS forum (
  fid INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  parent INT UNSIGNED NOT NULL DEFAULT 0,
  path VARCHAR(255) NOT NULL DEFAULT '0',
  depth TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `order` INT UNSIGNED NOT NULL DEFAULT 0,
  threads INT UNSIGNED NOT NULL DEFAULT 0,
  today INT UNSIGNED NOT NULL DEFAULT 0,
  posts INT UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_parent (parent),
  KEY idx_order (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tag 表
CREATE TABLE IF NOT EXISTS tag (
  tag_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  slug VARCHAR(60) NOT NULL,
  threads INT UNSIGNED NOT NULL DEFAULT 0,
  view INT UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_slug (slug),
  KEY idx_threads (threads),
  KEY idx_view (view)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ThreadTag 关联表
CREATE TABLE IF NOT EXISTS thread_tag (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tid BIGINT UNSIGNED NOT NULL,
  tag_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_tid (tid),
  KEY idx_tag_id (tag_id),
  UNIQUE KEY uk_tid_tagid (tid, tag_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ForumAccess 权限表
CREATE TABLE IF NOT EXISTS forum_access (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  fid INT UNSIGNED NOT NULL,
  gid INT UNSIGNED NOT NULL,
  `read` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  thread TINYINT UNSIGNED NOT NULL DEFAULT 0,
  reply TINYINT UNSIGNED NOT NULL DEFAULT 0,
  upload TINYINT UNSIGNED NOT NULL DEFAULT 0,
  download TINYINT UNSIGNED NOT NULL DEFAULT 0,
  KEY idx_fid (fid),
  KEY idx_gid (gid),
  UNIQUE KEY uk_fid_gid (fid, gid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
