-- WellCMS Go Headless - Thread Table Schema
-- Database: wellcms_go

-- Thread 主表（列表专用）
CREATE TABLE IF NOT EXISTS thread (
  tid BIGINT UNSIGNED PRIMARY KEY,
  fid INT UNSIGNED NOT NULL,
  uid BIGINT UNSIGNED NOT NULL,
  subject VARCHAR(120) NOT NULL,
  views INT UNSIGNED NOT NULL DEFAULT 0,
  replies INT UNSIGNED NOT NULL DEFAULT 0,
  dateline INT UNSIGNED NOT NULL,
  lastpost INT UNSIGNED NOT NULL,
  status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_fid_lastpost (fid, lastpost),
  KEY idx_uid (uid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Thread 内容表
CREATE TABLE IF NOT EXISTS thread_data (
  tid BIGINT UNSIGNED PRIMARY KEY,
  message MEDIUMTEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
